import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'

const Home = () => {
  return (
    <div className="container">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
      <h1>Home</h1>
      </div>
    </div>
  )
};
export default Home;
